import messages from '@/messages/messages'
import type {
  EmployeeCreateForm,
  EmployeeCreatePayload,
  EmployeeDetail,
  EmployeeDetailView,
  EmployeeUpdatePayload,
  EmployeePagedResponse,
  EmployeeRaw,
  EmployeeTableRow,
  EmployeesPagination,
  EmployeesQueryParams,
} from '@/types'
import { mapperPagination } from '../shared/pagination.mapper'
import { buildQueryParams, appendString, appendBooleanString, appendParsedId } from '../shared/queryParams.mapper'
import { parseRequiredNumber, parseNullableId, parseNullableNumber, parseNullableString } from '../shared/form.mapper'
import { formatDate } from '@/utils'

export function mapperEmployeesRows(response: EmployeeRaw[]): EmployeeTableRow[] {
  return response.map((item) => ({
    id: String(item.id),
    active: item.active,
    hasContract: item.hasContract,
    linkedUserId: item.userId ?? null,
    linkedUserName: item.username ?? null,
    linkedUserEmail: item.userEmail ?? null,
    values: [
      item.identification,
      `${item.firstName} ${item.paternalLastName} ${item.maternalLastName}`.trim(),
      item.corporateEmail,
      item.phone ?? '',
      item.statusName,
      item.hasContract ? messages.employees.ui.rehireEligibleYes : messages.employees.ui.rehireEligibleNo,
      item.active ? messages.employees.ui.statusActive : messages.employees.ui.statusInactive,
      formatDate(item.createdAt),
      formatDate(item.updatedAt),
      '',
    ],
  }))
}

export function mapperEmployeesPagination(response: EmployeePagedResponse): EmployeesPagination {
  return mapperPagination(response)
}

export function mapperEmployeesQueryParams(queryParams: EmployeesQueryParams): Record<string, string | number> {
  const params = buildQueryParams(queryParams)
  appendString(params, 'search', queryParams.search)
  appendBooleanString(params, 'active', queryParams.active)
  appendParsedId(params, 'statusId', queryParams.statusId)
  appendString(params, 'createdFrom', queryParams.createdFrom)
  appendString(params, 'createdTo', queryParams.createdTo)
  return params
}

export function mapperEmployeeDetailView(result: EmployeeDetail): EmployeeDetailView {
  return {
    id: String(result.id),
    fullName: `${result.firstName} ${result.paternalLastName} ${result.maternalLastName}`.trim(),
    active: result.active,
    statusName: result.status?.name || '',
    rehireEligible: result.rehireEligible,
    hasContract: result.hasContract,
    costCenterDisplay: result.costCenter != null ? String(result.costCenter) : '-',
    projectName: result.projectName || '-',
    identification: result.identification,
    identificationType: result.identificationType?.name || '',
    birthDate: result.birthDate || '',
    gender: result.gender?.name || '',
    maritalStatus: result.maritalStatus?.name || '',
    educationLevel: result.educationLevel?.name || '',
    driverLicense: result.driverLicense?.name || '',
    profession: result.profession?.name || '',
    nationality: result.nationality?.name || '',
    expat: result.expat?.name || '',
    personalEmail: result.personalEmail || '',
    corporateEmail: result.corporateEmail,
    phone: result.phone || '',
    phone2: result.phone2 || '',
    emergencyContactName: result.emergencyContactName || '',
    emergencyContactRelationship: result.emergencyContactRelationship?.name || '',
    emergencyContactPhone: result.emergencyContactPhone || '',
    emergencyContactPhone2: result.emergencyContactPhone2 || '',
    streetName: result.streetName || '',
    streetNumber: result.streetNumber || '',
    postalCode: result.postalCode || '',
    department: result.department || '',
    village: result.village || '',
    block: result.block || '',
    region: result.region?.name || '',
    commune: result.commune?.name || '',
    city: result.city?.name || '',
    familyAllowanceTier: result.familyAllowanceTier?.name || '',
    retirementStatus: result.retirementStatus?.name || '',
    isapreFun: result.isapreFun || '',
    pensionStatus: result.pensionStatus?.name || '',
    afp: result.afp?.name || '',
    healthInsurance: result.healthInsurance?.name || '',
    healthInsuranceTariff: result.healthInsuranceTariff?.name || '',
    healthInsuranceUF: result.healthInsuranceUF || '',
    healthInsurancePesos: result.healthInsurancePesos || '',
    paymentMethod: result.paymentMethod?.name || '',
    bank: result.bank?.name || '',
    bankAccount: result.bankAccount || '',
    clothingSize: result.clothingSize || '',
    shoeSize: result.shoeSize || '',
    pantSize: result.pantSize || '',
    username: result.username || '',
    userEmail: result.userEmail || '',
    userEnabled: result.userEnabled ?? null,
    requestId: result.requestId != null ? String(result.requestId) : 'Sin registro',
    createdAt: result.createdAt || '',
    createdAtDisplay: formatDate(result.createdAt, 'Sin registro'),
    updatedAtDisplay: formatDate(result.updatedAt, 'Sin registro'),
  }
}


export function mapperCreateEmployeePayload(form: EmployeeCreateForm): EmployeeCreatePayload {
  return {
    costCenter: parseRequiredNumber(form.costCenter),
    identification: form.identification.trim(),
    identificationTypeId: parseRequiredNumber(form.identificationTypeId),
    firstName: form.firstName.trim(),
    paternalLastName: form.paternalLastName.trim(),
    maternalLastName: form.maternalLastName.trim(),
    birthDate: form.birthDate.trim(),
    genderId: parseRequiredNumber(form.genderId),
    maritalStatusId: parseRequiredNumber(form.maritalStatusId),
    educationLevelId: parseRequiredNumber(form.educationLevelId),
    driverLicenseId: parseRequiredNumber(form.driverLicenseId),
    professionId: parseRequiredNumber(form.professionId),
    personalEmail: form.personalEmail.trim(),
    corporateEmail: form.corporateEmail.trim(),
    phone: form.phone.trim(),
    phone2: parseNullableString(form.phone2),
    emergencyContactName: form.emergencyContactName.trim(),
    emergencyContactRelationshipId: parseRequiredNumber(form.emergencyContactRelationshipId),
    emergencyContactPhone: form.emergencyContactPhone.trim(),
    emergencyContactPhone2: parseNullableString(form.emergencyContactPhone2),
    streetName: form.streetName.trim(),
    streetNumber: form.streetNumber.trim(),
    postalCode: form.postalCode.trim(),
    department: parseNullableString(form.department),
    village: parseNullableString(form.village),
    block: parseNullableString(form.block),
    regionId: parseRequiredNumber(form.regionId),
    communeId: parseRequiredNumber(form.communeId),
    cityId: parseRequiredNumber(form.cityId),
    expatId: parseRequiredNumber(form.expatId),
    nationalityId: parseRequiredNumber(form.nationalityId),
    familyAllowanceTierId: parseRequiredNumber(form.familyAllowanceTierId),
    retirementStatusId: parseRequiredNumber(form.retirementStatusId),
    isapreFun: parseNullableString(form.isapreFun),
    pensionStatusId: parseRequiredNumber(form.pensionStatusId),
    afpId: parseRequiredNumber(form.afpId),
    healthInsuranceId: parseRequiredNumber(form.healthInsuranceId),
    healthInsuranceTariffId: parseNullableNumber(form.healthInsuranceTariffId),
    healthInsuranceUF: parseNullableNumber(form.healthInsuranceUF),
    healthInsurancePesos: parseNullableNumber(form.healthInsurancePesos),
    paymentMethodId: parseRequiredNumber(form.paymentMethodId),
    bankId: parseRequiredNumber(form.bankId),
    bankAccount: form.bankAccount.trim(),
    clothingSize: form.clothingSize.trim(),
    shoeSize: form.shoeSize.trim(),
    pantSize: form.pantSize.trim(),
  }
}

export function mapperEmployeeDetailToForm(detail: EmployeeDetail): EmployeeCreateForm {
  return {
    costCenter: detail.costCenter != null ? String(detail.costCenter) : '',
    identification: detail.identification,
    identificationTypeId: detail.identificationType?.id ? String(detail.identificationType.id) : '',
    firstName: detail.firstName,
    paternalLastName: detail.paternalLastName,
    maternalLastName: detail.maternalLastName,
    birthDate: detail.birthDate ?? '',
    genderId: detail.gender?.id ? String(detail.gender.id) : '',
    maritalStatusId: detail.maritalStatus?.id ? String(detail.maritalStatus.id) : '',
    educationLevelId: detail.educationLevel?.id ? String(detail.educationLevel.id) : '',
    driverLicenseId: detail.driverLicense?.id ? String(detail.driverLicense.id) : '',
    professionId: detail.profession?.id ? String(detail.profession.id) : '',
    personalEmail: detail.personalEmail ?? '',
    corporateEmail: detail.corporateEmail,
    phone: detail.phone ?? '',
    phone2: detail.phone2 ?? '',
    emergencyContactName: detail.emergencyContactName ?? '',
    emergencyContactRelationshipId: detail.emergencyContactRelationship?.id ? String(detail.emergencyContactRelationship.id) : '',
    emergencyContactPhone: detail.emergencyContactPhone ?? '',
    emergencyContactPhone2: detail.emergencyContactPhone2 ?? '',
    streetName: detail.streetName ?? '',
    streetNumber: detail.streetNumber ?? '',
    postalCode: detail.postalCode ?? '',
    department: detail.department ?? '',
    village: detail.village ?? '',
    block: detail.block ?? '',
    regionId: detail.region?.id ? String(detail.region.id) : '',
    communeId: detail.commune?.id ? String(detail.commune.id) : '',
    cityId: detail.city?.id ? String(detail.city.id) : '',
    expatId: detail.expat?.id ? String(detail.expat.id) : '',
    nationalityId: detail.nationality?.id ? String(detail.nationality.id) : '',
    familyAllowanceTierId: detail.familyAllowanceTier?.id ? String(detail.familyAllowanceTier.id) : '',
    retirementStatusId: detail.retirementStatus?.id ? String(detail.retirementStatus.id) : '',
    isapreFun: detail.isapreFun ?? '',
    pensionStatusId: detail.pensionStatus?.id ? String(detail.pensionStatus.id) : '',
    afpId: detail.afp?.id ? String(detail.afp.id) : '',
    healthInsuranceId: detail.healthInsurance?.id ? String(detail.healthInsurance.id) : '',
    healthInsuranceTariffId: detail.healthInsuranceTariff?.id ? String(detail.healthInsuranceTariff.id) : '',
    healthInsuranceUF: detail.healthInsuranceUF ?? '',
    healthInsurancePesos: detail.healthInsurancePesos ?? '',
    paymentMethodId: detail.paymentMethod?.id ? String(detail.paymentMethod.id) : '',
    bankId: detail.bank?.id ? String(detail.bank.id) : '',
    bankAccount: detail.bankAccount ?? '',
    clothingSize: detail.clothingSize ?? '',
    shoeSize: detail.shoeSize ?? '',
    pantSize: detail.pantSize ?? '',
  }
}

export function mapperUpdateEmployeePayload(
  employeeId: number,
  form: EmployeeCreateForm,
  meta: { statusId: number, active: boolean, rehireEligible: boolean },
): EmployeeUpdatePayload {
  return {
    id: employeeId,
    costCenter: parseRequiredNumber(form.costCenter),
    identification: form.identification.trim(),
    identificationTypeId: parseRequiredNumber(form.identificationTypeId),
    firstName: form.firstName.trim(),
    paternalLastName: form.paternalLastName.trim(),
    maternalLastName: form.maternalLastName.trim(),
    birthDate: form.birthDate.trim(),
    genderId: parseRequiredNumber(form.genderId),
    maritalStatusId: parseRequiredNumber(form.maritalStatusId),
    educationLevelId: parseRequiredNumber(form.educationLevelId),
    driverLicenseId: parseRequiredNumber(form.driverLicenseId),
    professionId: parseRequiredNumber(form.professionId),
    personalEmail: form.personalEmail.trim(),
    corporateEmail: form.corporateEmail.trim(),
    phone: form.phone.trim(),
    phone2: parseNullableString(form.phone2),
    emergencyContactName: form.emergencyContactName.trim(),
    emergencyContactRelationshipId: parseRequiredNumber(form.emergencyContactRelationshipId),
    emergencyContactPhone: form.emergencyContactPhone.trim(),
    emergencyContactPhone2: parseNullableString(form.emergencyContactPhone2),
    streetName: form.streetName.trim(),
    streetNumber: form.streetNumber.trim(),
    postalCode: form.postalCode.trim(),
    department: parseNullableString(form.department),
    village: parseNullableString(form.village),
    block: parseNullableString(form.block),
    regionId: parseRequiredNumber(form.regionId),
    communeId: parseRequiredNumber(form.communeId),
    cityId: parseRequiredNumber(form.cityId),
    expatId: parseNullableId(form.expatId),
    nationalityId: parseRequiredNumber(form.nationalityId),
    familyAllowanceTierId: parseRequiredNumber(form.familyAllowanceTierId),
    retirementStatusId: parseRequiredNumber(form.retirementStatusId),
    isapreFun: parseNullableString(form.isapreFun),
    pensionStatusId: parseRequiredNumber(form.pensionStatusId),
    afpId: parseRequiredNumber(form.afpId),
    healthInsuranceId: parseRequiredNumber(form.healthInsuranceId),
    healthInsuranceTariffId: parseNullableNumber(form.healthInsuranceTariffId),
    healthInsuranceUF: parseNullableNumber(form.healthInsuranceUF),
    healthInsurancePesos: parseNullableNumber(form.healthInsurancePesos),
    paymentMethodId: parseRequiredNumber(form.paymentMethodId),
    bankId: parseRequiredNumber(form.bankId),
    bankAccount: form.bankAccount.trim(),
    clothingSize: form.clothingSize.trim(),
    shoeSize: form.shoeSize.trim(),
    pantSize: form.pantSize.trim(),
    statusId: meta.statusId,
    active: meta.active,
    rehireEligible: meta.rehireEligible,
  }
}
