export const REMEMBER_EMAIL_STORAGE_KEY = 'rememberEmail'

export const AUTH_ROUTE_LOGIN = '/login'
export const AUTH_ROUTE_REGISTER = '/register'
export const AUTH_ROUTE_LOGIN_CREDENTIALS = '/login/credentials'
export const AUTH_ROUTE_RECOVERY = '/recovery'
export const AUTH_ROUTE_VERIFY_EMAIL = '/verify-email'
export const AUTH_ROUTE_CREATE_PASSWORD = '/create-password'
export const AUTH_ROUTE_DASHBOARD = '/dashboard'
export const AUTH_ROUTE_SETTINGS = '/settings'
export const AUTH_ROUTE_USERS = '/users'
export const AUTH_ROUTE_DASHBOARD_EXAMPLE = '/dashboard-example'
export const AUTH_ROUTE_LOGOUT = '/logout'
export const AUTH_ROUTE_HOME = '/'
