import type { ValidationRule } from '@/types'

const selectRequiredRule = (label: string): ValidationRule => ({
  required: true,
  custom: (value: string) => (Number.isInteger(Number(value)) && Number(value) > 0 ? null : `Selecciona ${label}`),
})

export const employeesCreateValidationRules: Record<string, ValidationRule> = {
  identification: { required: true, minLength: 3 },
  identificationTypeId: selectRequiredRule('el tipo de identificacion'),
  firstName: { required: true, minLength: 2 },
  paternalLastName: { required: true, minLength: 2 },
  maternalLastName: { required: true, minLength: 2 },
  birthDate: { required: true },
  genderId: selectRequiredRule('el genero'),
  maritalStatusId: selectRequiredRule('el estado civil'),
  educationLevelId: selectRequiredRule('el nivel educacional'),
  driverLicenseId: selectRequiredRule('la licencia de conducir'),
  professionId: selectRequiredRule('la profesion'),
  personalEmail: { required: true, email: true },
  corporateEmail: { required: true, email: true },
  phone: { required: true, pattern: /^\+?[0-9]{8,15}$/ },
  emergencyContactName: { required: true, minLength: 2 },
  emergencyContactRelationshipId: selectRequiredRule('el parentesco del contacto de emergencia'),
  emergencyContactPhone: { required: true, pattern: /^\+?[0-9]{8,15}$/ },
  streetName: { required: true, minLength: 2 },
  streetNumber: { required: true, minLength: 1 },
  postalCode: { required: true, minLength: 4 },
  regionId: selectRequiredRule('la region'),
  communeId: selectRequiredRule('la comuna'),
  cityId: selectRequiredRule('la ciudad'),
  expatId: selectRequiredRule('la condicion de expatriado'),
  nationalityId: selectRequiredRule('la nacionalidad'),
  familyAllowanceTierId: selectRequiredRule('el tramo de carga familiar'),
  retirementStatusId: selectRequiredRule('el estado de retiro'),
  pensionStatusId: selectRequiredRule('el estado previsional'),
  afpId: selectRequiredRule('la AFP'),
  healthInsuranceId: selectRequiredRule('la previsión de salud'),
  paymentMethodId: selectRequiredRule('la forma de pago'),
  bankId: selectRequiredRule('el banco'),
  bankAccount: { required: true, minLength: 4 },
  clothingSize: { required: true, minLength: 1 },
  shoeSize: { required: true, minLength: 1 },
  pantSize: { required: true, minLength: 1 },
}
