export * from './assignments'
export * from './main'
export { default as ProjectSpecialtiesDashboardPage } from './ProjectSpecialtiesDashboardPage'
export { default as ProjectSpecialtiesFormDashboardPage } from './ProjectSpecialtiesFormDashboardPage'
export { default as ProjectStatusesDashboardPage } from './ProjectStatusesDashboardPage'
export { default as ProjectStatusesFormDashboardPage } from './ProjectStatusesFormDashboardPage'
export { default as ProjectTypesDashboardPage } from './ProjectTypesDashboardPage'
export { default as ProjectTypesFormDashboardPage } from './ProjectTypesFormDashboardPage'
