import type { EmployeeCreateForm, EmployeesPagination, EmployeesQueryParams, EmployeeTableRow } from '@/types'

export const employeesTableColumns: string[] = [
  'Identificacion',
  'Nombre',
  'Email',
  'Telefono',
  'Estado de aprobacion',
  'Recontratable',
  'Estado',
  'Creado',
  'Actualizado',
  'Acciones',
]

export const initialEmployeesRows: EmployeeTableRow[] = []

export const initialEmployeesPagination: EmployeesPagination = {
  page: 0,
  size: 8,
  totalElements: 0,
  totalPages: 0,
  total: 0,
  active: 0,
  first: true,
  last: true,
}

export const initialEmployeesQueryParams: EmployeesQueryParams = {
  page: 0,
  size: 8,
  search: '',
  active: '',
  statusId: '',
  createdFrom: '',
  createdTo: '',
  sortBy: 'createdAt',
  sortDir: 'desc',
}

export const initialCreateEmployeeForm: EmployeeCreateForm = {
  identification: '',
  identificationTypeId: '',
  firstName: '',
  paternalLastName: '',
  maternalLastName: '',
  birthDate: '',
  genderId: '',
  maritalStatusId: '',
  educationLevelId: '',
  driverLicenseId: '',
  professionId: '',
  personalEmail: '',
  corporateEmail: '',
  phone: '',
  phone2: '',
  emergencyContactName: '',
  emergencyContactRelationshipId: '',
  emergencyContactPhone: '',
  emergencyContactPhone2: '',
  streetName: '',
  streetNumber: '',
  postalCode: '',
  department: '',
  village: '',
  block: '',
  regionId: '',
  communeId: '',
  cityId: '',
  expatId: '',
  nationalityId: '',
  familyAllowanceTierId: '',
  retirementStatusId: '',
  isapreFun: '',
  pensionStatusId: '',
  afpId: '',
  healthInsuranceId: '',
  healthInsuranceTariffId: '',
  healthInsuranceUF: '',
  healthInsurancePesos: '',
  paymentMethodId: '',
  bankId: '',
  bankAccount: '',
  clothingSize: '',
  shoeSize: '',
  pantSize: '',
}
